### ISSUE TITLE
Allow Webform to be used with the D.T admin role

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-webform#44]
If a user only has the dt admin role, then they can't access the webform settings.

**Comment by squigglybob** [comment]
@corsacca I can take this one

**Comment by squigglybob** [comment]
webform settings seem to be accessible with only dt_admin role set.
Maybe this is already fixed?

**Comment by squigglybob** [comment]
Nope it wasn't fixed. Clicking on 'add new form' resulted in the permission denied error which states that the user can't create a page.

I've changed the `dt_webform` post type to have `capability_type => 'post'` instead of page, and that seems to fix it.

@ChrisChasm  @corsacca 
Is it ok to change the capability type on this posttype? Or would it be better to add the capability of editing a page to the dt_admin role?
